# Generated by Django 3.2.5 on 2021-07-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dsuser',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(max_length=255, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='패스워드')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'dsuser',
            },
        ),
    ]
